use std::fs;
use std::io::Write;
use glob::glob;

#[derive(Debug)]
struct PuzzleDiscovery {
    day: u8,
    part: u8,
    module_name: String,
}

fn puzzles() -> Vec<PuzzleDiscovery> {
    let mut puzzles = Vec::new();
    for day in 1..=24 {
        for part in 1..=2 {
            let module_name = format!("day{:02}_part{}", day, part);
            let file_exists = fs::exists(format!("src/solutions/{}.rs", module_name));
            if file_exists.is_ok() && !file_exists.unwrap() {
                continue;
            }
            puzzles.push(PuzzleDiscovery { day, part, module_name: module_name });
        }
    }
    puzzles
}

fn configure_build() {
    let files = glob("src/**/*.rs").unwrap();
    for file in files {
        match file {
            Ok(path) => {
                println!("cargo:rerun-if-changed={}", path.display());
            }
            Err(e) => println!("Error reading file: {:?}", e),
        }
    }
}

fn template_head() -> String {
    "// This file is automatically generated by build.rs

#[derive(Debug, Clone)]
pub struct Puzzle {
    pub day: u8,
    pub part: u8,
    pub main: fn()
}
".to_string()
}

fn template_logic() -> String {
    "pub fn run(puzzle: Option<(u8, u8)>) -> Option<Puzzle> {
    {{puzzles_definition}}

    if puzzle.is_some() {
        let (day, part) = puzzle.unwrap();
        let puzzle: Vec<&Puzzle> = puzzles.iter().filter(|e| {
            e.day == day && e.part == part
        }).collect();
    
        if puzzle.len() == 0 {
            return None;
        }

        let puzzle = puzzle[0];
        return Some(puzzle.clone());
    } else {
        let latest = puzzles.last();
        if latest.is_some() {
            let latest = latest.unwrap();
            return Some(latest.clone());
        }
    }
    return None;
}".to_string()
}

fn main() {
    configure_build();

    let selector_path = "src/selector.rs";
    let modules_path = "src/solutions/mod.rs";
    let mut selector_file = fs::File::create(&selector_path).unwrap();
    let mut modules_file = fs::File::create(&modules_path).unwrap();

    writeln!(selector_file, "{}", template_head()).unwrap();

    //writeln!(file, "{}", "#[test]").unwrap();
    let puzzles = puzzles();
    let mut puzzles_definition = "let puzzles: Vec<Puzzle> = vec![".to_string();
    for puzzle in &puzzles {
        puzzles_definition.push_str(&format!("\n        Puzzle {{ day: {}, part: {}, main: crate::solutions::{}::main }},", puzzle.day, puzzle.part, puzzle.module_name));
    }
    puzzles_definition.push_str("\n    ];");

    let modules_definition = &puzzles.iter().map(|puzzle| {
        format!("pub mod {};", puzzle.module_name)
    }).collect::<Vec<String>>().join("\n");

    writeln!(selector_file, "{}", template_logic().replace("{{puzzles_definition}}", &puzzles_definition)).unwrap();

    writeln!(modules_file, "{}", modules_definition).unwrap();
}