// This file is automatically generated by build.rs

#[derive(Debug, Clone)]
pub struct Puzzle {
    pub day: u8,
    pub part: u8,
    pub main: fn()
}

pub fn run(puzzle: Option<(u8, u8)>) -> Option<Puzzle> {
    let puzzles: Vec<Puzzle> = vec![
        Puzzle { day: 1, part: 1, main: crate::solutions::day01_part1::main },
        Puzzle { day: 1, part: 2, main: crate::solutions::day01_part2::main },
        Puzzle { day: 2, part: 1, main: crate::solutions::day02_part1::main },
        Puzzle { day: 2, part: 2, main: crate::solutions::day02_part2::main },
        Puzzle { day: 3, part: 1, main: crate::solutions::day03_part1::main },
        Puzzle { day: 3, part: 2, main: crate::solutions::day03_part2::main },
        Puzzle { day: 4, part: 1, main: crate::solutions::day04_part1::main },
        Puzzle { day: 4, part: 2, main: crate::solutions::day04_part2::main },
        Puzzle { day: 5, part: 1, main: crate::solutions::day05_part1::main },
        Puzzle { day: 5, part: 2, main: crate::solutions::day05_part2::main },
        Puzzle { day: 6, part: 1, main: crate::solutions::day06_part1::main },
        Puzzle { day: 6, part: 2, main: crate::solutions::day06_part2::main },
        Puzzle { day: 7, part: 1, main: crate::solutions::day07_part1::main },
        Puzzle { day: 7, part: 2, main: crate::solutions::day07_part2::main },
        Puzzle { day: 8, part: 1, main: crate::solutions::day08_part1::main },
        Puzzle { day: 9, part: 1, main: crate::solutions::day09_part1::main },
        Puzzle { day: 9, part: 2, main: crate::solutions::day09_part2::main },
    ];

    if puzzle.is_some() {
        let (day, part) = puzzle.unwrap();
        let puzzle: Vec<&Puzzle> = puzzles.iter().filter(|e| {
            e.day == day && e.part == part
        }).collect();
    
        if puzzle.len() == 0 {
            return None;
        }

        let puzzle = puzzle[0];
        return Some(puzzle.clone());
    } else {
        let latest = puzzles.last();
        if latest.is_some() {
            let latest = latest.unwrap();
            return Some(latest.clone());
        }
    }
    return None;
}
